### ISSUE TITLE
Crash on update_index

### ISSUE THREAD

**Issue by Ch4s3** [toptal/chewy#233]
I have a model that generates a Postgres UUID on create (at the db level) and gets reloaded after save so the UUID is available. 

Then I run the following:
```ruby
authorization.update_attribute(:outcome, "Sent") if json["isSuccess"]
```

And get the following crash:
```
Puma caught this error: Import failed for `AuthorizationsIndex::Authorization` with:
    Index errors:
      `WriteFailureException; nested: MapperParsingException[object mapping for [authorization] tried to parse field [organization] as object, but got EOF, has a concrete value been provided to it?]; `
        on 1 documents: ["20"]
 (Chewy::ImportFailed)
/Users/chase/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.1/lib/chewy/type/import.rb:61:in `import!'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.1/lib/chewy/strategy/atomic.rb:27:in `block in leave'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.1/lib/chewy/strategy/atomic.rb:27:in `each'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.1/lib/chewy/strategy/atomic.rb:27:in `all?'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.1/lib/chewy/strategy/atomic.rb:27:in `leave'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.1/lib/chewy/strategy.rb:48:in `tap'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.1/lib/chewy/strategy.rb:48:in `pop'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.1/lib/chewy/strategy.rb:56:in `wrap'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.1/lib/chewy.rb:160:in `strategy'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.1/lib/chewy/railtie.rb:16:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.12/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/lock.rb:17:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/rack-zippy-3.0.1/lib/rack-zippy.rb:55:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/rack-mini-profiler-0.9.6/lib/mini_profiler/profiler.rb:279:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/railties-4.1.12/lib/rails/engine.rb:514:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/railties-4.1.12/lib/rails/application.rb:144:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/puma-2.12.2/lib/puma/server.rb:539:in `handle_request'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/puma-2.12.2/lib/puma/server.rb:386:in `process_client'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/puma-2.12.2/lib/puma/server.rb:269:in `block in run'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/puma-2.12.2/lib/puma/thread_pool.rb:106:in `call'
/Users/chase/.rvm/gems/ruby-2.2.2/gems/puma-2.12.2/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by pyromaniac** [comment]
It seems like there is a problem with your mapping. `organization` field is defined as `object`, but there was nil provided probably instead of `{}`

**Comment by Ch4s3** [comment]
Odd, my schema has it as a string, and its present when I'm indexing here.

**Comment by pyromaniac** [comment]
But the message `tried to parse field [organization] as object, but got EOF, has a concrete value been provided to it?` means exactly what I've described. Also there might be a chance that you didn't apply mapping at all. You have to do `YourIndex.create!` before the first import

**Comment by Ch4s3** [comment]
I think I figured it out. It seems like the index was set up incorrectly.
