### ISSUE TITLE
Importing list of IDs fails

### ISSUE THREAD

**Issue by gmile** [toptal/chewy#246]
For some reason I'm getting an exception.

```
2.1.4 :001 > ProductIndex.import([384, 385])
TypeError: no implicit conversion of Symbol into Integer
	from /Users/gmile/.rvm/gems/ruby-2.1.4@portal/gems/chewy-0.8.1/lib/chewy/index/actions.rb:145:in `[]'
	from /Users/gmile/.rvm/gems/ruby-2.1.4@portal/gems/chewy-0.8.1/lib/chewy/index/actions.rb:145:in `block in import'
	from /Users/gmile/.rvm/gems/ruby-2.1.4@portal/gems/chewy-0.8.1/lib/chewy/index/actions.rb:144:in `map'
	from /Users/gmile/.rvm/gems/ruby-2.1.4@portal/gems/chewy-0.8.1/lib/chewy/index/actions.rb:144:in `import'
	from (irb):1
	from /Users/gmile/.rvm/gems/ruby-2.1.4@portal/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/gmile/.rvm/gems/ruby-2.1.4@portal/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/gmile/.rvm/gems/ruby-2.1.4@portal/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/gmile/.rvm/gems/ruby-2.1.4@portal/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/gmile/.rvm/gems/ruby-2.1.4@portal/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

@pyromaniac, what else data I can provide to help investigate this?

**Comment by pyromaniac** [comment]
Since there might me several types inside one index, chewy has no idea which one are you going to import, so you have to specify it: `ProductIndex::Product.import([384, 385])` or `ProductIndex.import(product: [384, 385])`

But I would agree, I have to work on error handling here :)

**Comment by gmile** [comment]
You're absolutely right, I used it in a wrong way. This worked perfectly fine for me:

```ruby
ProductIndex.import(product: [384, 385])
```

Looks like I was using incorrect syntax.
