### ISSUE TITLE
Problem with attachment plugin?

### ISSUE THREAD

**Issue by sasselin** [toptal/chewy#259]
I added the plugin to index attachments in elasticsearch

https://github.com/elastic/elasticsearch-mapper-attachments

Work fine with chewy, but, if I have more of 20 documents. The "rake chewy:reset" log this:

How could I fix this problem? I think that indexing batch work. But how did it?
Thank you

```
rake aborted!
Errno::EPIPE: Broken pipe
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/transport/base.rb:191:in `call'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/transport/base.rb:191:in `perform_request'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/client.rb:119:in `perform_request'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/elasticsearch-api-1.0.13/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/chewy/type/import.rb:70:in `bulk'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/chewy/type/import.rb:32:in `block (2 levels) in import'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/chewy/type/adapter/active_record.rb:25:in `import_scope'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/chewy/type/adapter/orm.rb:84:in `import'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/chewy/type/import.rb:28:in `block in import'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/chewy/type/import.rb:27:in `import'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/chewy/index/actions.rb:146:in `block in import'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/chewy/index/actions.rb:144:in `map'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/chewy/index/actions.rb:144:in `import'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/chewy/index/actions.rb:177:in `reset!'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/tasks/chewy.rake:32:in `reset_index'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/tasks/chewy.rake:37:in `block in reset_all'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/tasks/chewy.rake:37:in `each'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/tasks/chewy.rake:37:in `reset_all'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/gems/chewy-0.8.1/lib/tasks/chewy.rake:59:in `block (2 levels) in <top (required)>'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/sebastienasselin/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => chewy:reset
(See full trace by running task with --trace)
```

**Comment by pyromaniac** [comment]
Take a look on ES logs at first. I can assume that files are encoded somehow inside index command body, but since chewy uses indexing in batches - the size of batch became too big to handle. Maybe there are some option in ES or you can decrease batch size to 10 in import.

**Comment by sasselin** [comment]
This is not your plugin problem. I have a TooLongFrameException in log.

But, I don't find a configuration to decrease batch size...

Thank you for your help

**Comment by pyromaniac** [comment]
https://github.com/toptal/chewy/blob/master/lib/chewy/type/import.rb#L16 like this, but it is not configurable unfortunately. Probably some codebase changes required here. Also it would be great for you to have separate batch sizes for AR records fetching and ES indexing. It would be more efficient
