### ISSUE TITLE
unable to reset the index

### ISSUE THREAD

**Issue by ayumi5** [toptal/chewy#276]
Hi,

I'm having trouble when trying to reset the index. It returns this error:
```
irb(main):001:0> NotesIndex.reset!
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/ayumi/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/chewy-0.8.2/lib/chewy/runtime.rb:6:in `version'
from /Users/ayumi/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/chewy-0.8.2/lib/chewy/index/actions.rb:59:in `create!'
from /Users/ayumi/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/chewy-0.8.2/lib/chewy/index/actions.rb:127:in `purge!'
from /Users/ayumi/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/chewy-0.8.2/lib/chewy/index/actions.rb:176:in `reset!'
```
Here are the chewy settings and object I made:
```
#config/initializers/chewy.rb
Chewy.settings = {host: 'localhost:3000 '}

#app/chewy/notes_index.rb
class NotesIndex < Chewy::Index
  settings analysis: {
    analyzer: {
      title: {
        tokenizer: 'standard',
        filter: ['lowercase']
      }
    }
  }
  
  define_type Note do
    field :title
    field :content
    field :category, value: -> { category }
    field :url
    field :updated, type: 'date', include_in_all: false, value: -> { updated_at }
  end
end
```
Am I missing something?

**Comment by pyromaniac** [comment]
It seems like there is no ElasticSearch running on localhost:3000

**Comment by ayumi5** [comment]
oh right! Thanks :)
