### ISSUE TITLE
insert RequestStrategy after Rails::Rack::Logger fails

### ISSUE THREAD

**Issue by jphelps413** [toptal/chewy#286]
In railtie.rb(v0.8.2) this code:

```
initializer 'chewy.request_strategy' do |app|
    app.config.middleware.insert_after(Rails::Rack::Logger, RequestStrategy)
end
```

the middleware insert will fail if the Rails::Rack::Logger has already been swapped out by something like Silencer::Logger. Perhaps we should be handling the initialization of Silencer in a different fashion, or is this something the chewy code should detect and handle?

**Comment by pyromaniac** [comment]
For such a custom cases you can do the same in your application.rb manually to put RequestStrategy after any other convenient middleware.

**Comment by jphelps413** [comment]
Pardon my ignorance on this, but we are not directly using RequestStrategy anywhere in our code. I assume it is being referenced by some other call, perhaps by a method which invokes Chewy.strategy( :atomic, &block )? To be clear, this problem occurs on startup initialization so the system never gets up and running.

**Comment by pyromaniac** [comment]
Well, now I'm confused, could you describe the problem please? I didn't get it.

**Comment by jphelps413** [comment]
My apologies for not providing more detail in the initial posting. In our configurations for production and staging we employ the silencer gem https://github.com/stve/silencer to squelch the log statements caused by the AWS load balancer health checks. In our startup initialization for these environments we do:
```
  # include a custom logger to silence aws health checks
  config.middleware.swap Rails::Rack::Logger, Silencer::Logger, silence: ["/health-check"]
```
This causes the insert_after call in request_strategy to die since Rails::Rack::Logger has been swapped out. I am not yet familiar enough with how we are using chewy to be able to properly work around this problem other than sticking with 0.8.1 for now, which is fine in our case.

**Comment by pyromaniac** [comment]
Is it dying silently or with exception?

**Comment by jphelps413** [comment]
```
=> Booting WEBrick
=> Rails 4.2.5 application starting in dev on http://localhost:3000
2015-11-25T14:29:01.778Z 7538 TID-anm28 INFO: configuring sidekiq client to connect to redis://localhost:6379
Exiting
/home/john/.rvm/gems/ruby-2.2.3@fractograf/gems/actionpack-4.2.5/lib/action_dispatch/middleware/stack.rb:125:in `assert_index': No such middleware to insert after: Rails::Rack::Logger (RuntimeError)
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/actionpack-4.2.5/lib/action_dispatch/middleware/stack.rb:96:in `insert_after'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/configuration.rb:68:in `block in merge_into'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/configuration.rb:67:in `each'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/configuration.rb:67:in `merge_into'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/engine.rb:501:in `app' 
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run' 
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /app/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /app/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /app/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /app/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /app/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /app/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /app/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /app/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /app/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `public_send'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/railtie.rb:194:in `method_missing'
        from /app/ff-yam/config/environment.rb:5:in `<top (required)>'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
        from /app/ff-yam/config.ru:3:in `block in <main>'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from /app/ff-yam/config.ru:in `new'
        from /app/ff-yam/config.ru:in `<main>'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/rack-1.6.4/lib/rack/server.rb:208:in `app' 
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/commands/server.rb:61:in `app' 
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/commands/server.rb:80:in `start'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap' 
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /app/.rvm/gems/ruby-2.2.3@fractograf/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by pyromaniac** [comment]
Wow, sorry, I've completely lost this conversation. So the best thing here I could offer - is to provide configuration option for the middleware. Also you may try to put chewy gem above those silencer in your Gemfile, this will probably help instantly

**Comment by jphelps413** [comment]
No worries, we all get busy. Moving the location of the gem doesn't have any effect, oddly enough. We already have chewy as one of the first and silencer as one of the last. We're fine locked in at 0.8.1 so feel free to back burner this.
