### ISSUE TITLE
Dynamic fields in indexing not working properly

### ISSUE THREAD

**Issue by mikeyhogarth** [toptal/chewy#320]
We've defined the following field (hard-coded purely for this example)

```
field :meta_attributes, type: 'object', value: -> { { color: :blue } }
```

And now all of our tests are giving us backtraces:

```
     Failure/Error: product = create(:product, :with_meta)

     Chewy::ImportFailed:
       Import failed for `ProductsIndex::Product` with:
           Index errors:
             `{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [meta_attributes]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"unknown property [color]"}}`
               on 1 documents: ["1"]
     # ...gems/chewy-0.8.3/lib/chewy/type/import.rb:59:in `import!'
     # ...gems/chewy-0.8.3/lib/chewy/strategy/urgent.rb:13:in `update'
     # ...gems/chewy-0.8.3/lib/chewy/type/observe.rb:70:in `update_index'
     # ...gems/chewy-0.8.3/lib/chewy/type/observe.rb:28:in `block in update_proc'
```

the `meta_attibutes` field is dynamic, it can change depending on the product, but parking that for a second surely the above should work when it's hard coded?

Is this possibly some configuration issue we're not setting?

**Comment by pyromaniac** [comment]
Which ES version do you have?

**Comment by mikeyhogarth** [comment]
```
Version: 2.0.2, Build: 6abf5d8/2015-12-16T12:49:58Z, JVM: 1.8.0_60
```

**Comment by pyromaniac** [comment]
Well, I'm not sure, but try to take a look on exact document structure, could you post it?

**Comment by mikeyhogarth** [comment]
It's literally just this:
```
{
   "took": 93,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 1,
      "hits": [
         {
            "_index": "development_products",
            "_type": "product",
            "_id": "19",
            "_score": 1,
            "_source": {
               "title": "Product 19 - Ergonomic Aluminum Keyboard",
               "description": "Product 19\n\nDoloremque sunt est impedit consequatur porro ipsum ut. Ad aut quia voluptas. Et est voluptatem illum tenetur.\nDolorem voluptatem commodi soluta esse sunt provident. Sed ea natus possimus quibusdam accusamus. Sunt id rerum aut eaque eum assumenda. Nihil sit ut. A perspiciatis non doloribus delectus eaque.\nDeserunt culpa doloribus. Ut at quasi voluptatibus pariatur omnis placeat. Dolor nulla consequuntur neque numquam soluta.",
               "meta_attributes": {
                  "color": "blue"
               }
            }
         }
      ]
   }
}
```

This actually works in practice, it's just the tests that are failing (that message comes from a factory girl call)

**Comment by pyromaniac** [comment]
Ah, interesting, If it works, you have to debug it in specs I suppose. Haven't face with such an error

**Comment by pyromaniac** [comment]
Maybe it makes sense to set up `:bypass` strategy in tests

**Comment by mikeyhogarth** [comment]
Managed to get it working like this: 

```ruby
field :meta, type: 'object', value: ->(flobalob) {
       Hash[flobalob.meta.map {|x| [x.key, x.value] }]
}
```
