### ISSUE TITLE
Script errors after upgrading to Chewy 0.8.3 and Elasticsearch 2.2.0

### ISSUE THREAD

**Issue by eliduke** [toptal/chewy#344]
Recently upgraded and now when I try start up the elasticsearch test server with `rake elasticsearch:start`, I am getting the following error:

```
$ rake elasticsearch:start
Starting 1 Elasticsearch nodes.....Exception in thread "main" java.lang.IllegalArgumentException: script.disable_dynamic is not a supported setting, replace with fine-grained script settings. 
Dynamic scripts can be enabled for all languages and all operations by replacing `script.disable_dynamic: false` with `script.inline: on` and `script.indexed: on` in elasticsearch.yml
    at org.elasticsearch.script.ScriptService.<init>(ScriptService.java:144)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at <<<guice>>>
    at org.elasticsearch.node.Node.<init>(Node.java:200)
    at org.elasticsearch.node.Node.<init>(Node.java:128)
    at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
...........................rake aborted!
Timeout::Error: execution expired
/Users/eliduke/.rvm/gems/ruby-2.2.2/gems/elasticsearch-extensions-0.0.18/lib/elasticsearch/extensions/test/cluster.rb:240:in `sleep'
/Users/eliduke/.rvm/gems/ruby-2.2.2/gems/elasticsearch-extensions-0.0.18/lib/elasticsearch/extensions/test/cluster.rb:240:in `block (2 levels) in __wait_for_status'
/Users/eliduke/.rvm/gems/ruby-2.2.2/gems/elasticsearch-extensions-0.0.18/lib/elasticsearch/extensions/test/cluster.rb:225:in `loop'
/Users/eliduke/.rvm/gems/ruby-2.2.2/gems/elasticsearch-extensions-0.0.18/lib/elasticsearch/extensions/test/cluster.rb:225:in `block in __wait_for_status'
/Users/eliduke/.rvm/gems/ruby-2.2.2/gems/elasticsearch-extensions-0.0.18/lib/elasticsearch/extensions/test/cluster.rb:224:in `__wait_for_status'
/Users/eliduke/.rvm/gems/ruby-2.2.2/gems/elasticsearch-extensions-0.0.18/lib/elasticsearch/extensions/test/cluster.rb:206:in `wait_for_green'
/Users/eliduke/.rvm/gems/ruby-2.2.2/gems/elasticsearch-extensions-0.0.18/lib/elasticsearch/extensions/test/cluster.rb:130:in `start'
/Users/eliduke/.rvm/gems/ruby-2.2.2/gems/elasticsearch-extensions-0.0.18/lib/elasticsearch/extensions/test/cluster/tasks.rb:6:in `block (2 levels) in <top (required)>'
/Users/eliduke/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/eliduke/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => elasticsearch:start
(See full trace by running task with --trace)
```

The weird thing is that I can't find any mention of `script.disable_dynamic` currently in the `.yml`. I'm not setting that to begin with, so why is it barking at me? This wasn't a problem before upgrading, so obviously something has changed. So, I tried adding those two snippets that the error message indicated to the `.yml` but that doesn't seem to fix anything. I can't figure out how to get the test server running. The `chewy.yml` file hasn't changed:

```
test:
  host: '127.0.0.1:9250'
  prefix: 'test'
development:
  host: '127.0.0.1:9200'
```

Any thoughts on this?

**Comment by pyromaniac** [comment]
Didn't use ES 2.2, so didn't see such a problem yet, but the point is that this rake task is actually provided  by elasticsearch-ruby gem, so maybe you will be able to find clues there.

**Comment by eliduke** [comment]
When I do a google search for `rake elasticsearch:start` the only results that are found relate to chewy. Is chewy somehow the only tool using those tasks?

**Comment by pyromaniac** [comment]
https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-extensions#testcluster

**Comment by pyromaniac** [comment]
https://github.com/toptal/chewy/blob/ef0fab43cbd302997fcc2b2ae3b400ff97687f4c/Rakefile#L3
