### ISSUE TITLE
Error when attempting to use Chewy.strategy(:sidekiq) with mongoid

### ISSUE THREAD

**Issue by trystant** [toptal/chewy#378]
Hi,

First, thanks for chewy; it's making a fair amount of our ES related tasks easier. That being said, I'm running into a problem when trying to use the sidekiq strategy with mongoid.

Here's an excerpt from the controller in our project, both within `:create` and `:update` actions:
Create:
```
Chewy.strategy(:sidekiq) do
  if @user.save
    respond_with( {}, :location => 'nil' )
  else
    render_errors @user
  end
end
```

Update:
```
Chewy.strategy(:sidekiq) do
  @user.update_attributes( params[:user].permit! )
end
```

We're using chewy version (0.8.4) and a mongoid version pre-4 (the ref is 77e5875873d4a42d0d3fcbcac648d3845cf4b227) 

The error message we're getting is:
```
2016-04-22T15:21:45Z 91546 TID-owh463hy8 WARN: undefined method `_id' for "570fdb6275736e5867010000":String
2016-04-22T15:21:45Z 91546 TID-owh463hy8 WARN: /Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/fields/base.rb:48:in `compose'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/fields/base.rb:63:in `block in compose_children'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/fields/base.rb:63:in `map'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/fields/base.rb:63:in `compose_children'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/fields/base.rb:54:in `compose'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:180:in `object_data'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:147:in `index_bulk_entry'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:106:in `block (2 levels) in bulk_body'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:106:in `each'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:106:in `flat_map'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:106:in `block in bulk_body'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:103:in `each'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:103:in `flat_map'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:103:in `bulk_body'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:35:in `block (2 levels) in import'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/adapter/object.rb:64:in `block in import_objects'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/adapter/object.rb:63:in `each_slice'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/adapter/object.rb:63:in `each'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/adapter/object.rb:63:in `map'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/adapter/object.rb:63:in `import_objects'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/adapter/object.rb:42:in `import'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:33:in `block in import'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/activesupport-4.1.14.2/lib/active_support/notifications.rb:159:in `block in instrument'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/activesupport-4.1.14.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/activesupport-4.1.14.2/lib/active_support/notifications.rb:159:in `instrument'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:32:in `import'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/type/import.rb:56:in `import!'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/chewy-0.8.4/lib/chewy/strategy/sidekiq.rb:17:in `perform'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/chain.rb:122:in `call'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/statsd-ruby-1.2.1/lib/statsd.rb:232:in `time'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-pro-1.7.0/lib/sidekiq/middleware/server/statsd.rb:30:in `call'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-middleware-0.3.0/lib/sidekiq-middleware/server/unique_jobs.rb:18:in `call'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-pro-1.7.0/lib/sidekiq/batch/middleware.rb:26:in `call'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/logging.rb:22:in `with_context'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/chain.rb:127:in `call'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/middleware/chain.rb:127:in `invoke'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/processor.rb:51:in `block in process'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/processor.rb:94:in `stats'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/sidekiq-3.1.4/lib/sidekiq/processor.rb:50:in `process'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
/Users/marnyon/.rvm/gems/ruby-2.0.0-p648@client_app/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

The specific point of failure is in `lib/chewy/fields/base.rb`

```
def compose_children(value, *parent_objects)
  children.map { |field| field.compose(value, *parent_objects) }.compact.inject(:merge) if value
end
```

I'm going to continue to investigate this failure, but I opened this to see if there are any obvious things that I should be doing.

Also, the chewy README has the sentence "Patch Chewy::Strategy::Sidekiq::Worker for index updates improving."
<img width="918" alt="screen shot 2016-04-22 at 11 30 58 am" src="https://cloud.githubusercontent.com/assets/13509/14746485/de992112-087d-11e6-9cfe-0d2a17065a5b.png">

What patchwork needs to be done?
Thanks much,

**Comment by pyromaniac** [comment]
Thanks for your testimonial. It seems like not patchwork is required for you right now. And this looks like a bug actually. The problem is that `compose_children` gets string id instead of mongoid document somehow. I'll take a look where is it happen, but now sure when. Would be great if you will try to find the cause. Is atomic strategy working for you at the same actions. Maybe the cause is in how does sidekick serializes mongoid documents.

**Comment by trystant** [comment]
Thanks for the quick response. It looks like #213 raised a similar issue, but I tried forking the repo and incorporating those changes (https://github.com/trystant/chewy) without success. 

The urgent strategy works and so atomic should also work, I believe (since they're both derived from base), but I'll confirm.

It looks like the `import_objects` method in `lib/chewy/type/adapter/object.rb` is getting called at line 33 in `lib/chewy/type/import.rb`, rather than the `import_objects` in  `lib/chewy/type/adapter/orm.rb`. Does that help?

**Comment by pyromaniac** [comment]
> It looks like the import_objects method in lib/chewy/type/adapter/object.rb is getting called at line 33 in lib/chewy/type/import.rb, rather than the import_objects in lib/chewy/type/adapter/orm.rb. Does that help?

Yeah, the orm one have to be called, can you find out why?

**Comment by pyromaniac** [comment]
Also can you show your type definition?

**Comment by trystant** [comment]
Here's  the type definition:
```
 define_type User do
    field :_id, index: 'no'
    field :first_name, search_analyzer: 'full_name', index_analyzer: 'partial_name'
    field :last_name, search_analyzer: 'full_name', index_analyzer: 'partial_name'
    field :type, index: 'no', value: ->( type ) {'User'}
  end
```

Do you need the whole index.rb file?

Thanks again. I'll look into why `import_objects` isn't using the orm adapter.

**Comment by pyromaniac** [comment]
Everything seems to be fine with the type definition.

>  I'll look into why import_objects isn't using the orm adapter.

Yep, do it please

**Comment by trystant** [comment]
Cool, I'll take a look and let you know what I find.

**Comment by trystant** [comment]
So, doing more research, it seems that while chewy running under Rails will select the mongoid adapter, The Chewy worker running in sidekiq running the import ends up selecting the object adapter instead. I'm trying to see if there's a way to explicitly set the adapter based upon chewy and/or sidekiq settings.

If this rings any bells, please let me know. Otherwise, I'll continue to dig.

Thanks,
Mark

**Comment by pyromaniac** [comment]
Is sidekiq using some other gemfile then app?

**Comment by trystant** [comment]
No, it's not. Same Gemfile & codebase as the Rails app.

**Comment by pyromaniac** [comment]
So strange, didn't notice any problems with adapter detection, you may want to debug it.

**Comment by trystant** [comment]
If you can point me at the adapter detection code (in addition to anything in `create_type` in `lib/chewy.rb`), I'll debug in that general area.

**Comment by pyromaniac** [comment]
Nothing else AFAIR, if `accepts?` bypassing mongoid somehow - you have to find a reason.

**Comment by trystant** [comment]
So before going into `accepts?`, here's some output from `create_type` in `chewy.rb`
It looks like the types that are created in the portal_index file (e.g. "User") are not matching the type that is instantiated by the Sidekiq worker (e.g. "PortalIndex::User"). The Object adapter ends up getting selected as a result of that mismatch. What's the easiest way to either modify the worker so that it instantiates the proper class and its corresponding adapter? 

Thanks,
Mark

```
2016-05-12T17:43:31Z 6436 TID-owz3yln8k INFO: Booting Sidekiq 3.1.4 with redis options {:url=>"redis://localhost:6379", :namespace=>"sidekiq"}
"ADAPTERS: "
[
    [0] Chewy::Type::Adapter::ActiveRecord < Chewy::Type::Adapter::Orm,
    [1] Chewy::Type::Adapter::Mongoid < Chewy::Type::Adapter::Orm,
    [2] Chewy::Type::Adapter::Sequel < Chewy::Type::Adapter::Orm,
    [3] Chewy::Type::Adapter::Object < Chewy::Type::Adapter::Base
]
"INDEX: PortalIndex TARGET=User ADAPTER=#<Chewy::Type::Adapter::Mongoid:0x007fdbb9c1e430>"
"ADAPTERS: "
[
    [0] Chewy::Type::Adapter::ActiveRecord < Chewy::Type::Adapter::Orm,
    [1] Chewy::Type::Adapter::Mongoid < Chewy::Type::Adapter::Orm,
    [2] Chewy::Type::Adapter::Sequel < Chewy::Type::Adapter::Orm,
    [3] Chewy::Type::Adapter::Object < Chewy::Type::Adapter::Base
]
"INDEX: PortalIndex TARGET=Account ADAPTER=#<Chewy::Type::Adapter::Mongoid:0x007fdb9aa39e90>"
"ADAPTERS: "
[
    [0] Chewy::Type::Adapter::ActiveRecord < Chewy::Type::Adapter::Orm,
    [1] Chewy::Type::Adapter::Mongoid < Chewy::Type::Adapter::Orm,
    [2] Chewy::Type::Adapter::Sequel < Chewy::Type::Adapter::Orm,
    [3] Chewy::Type::Adapter::Object < Chewy::Type::Adapter::Base
]
"INDEX: PortalIndex TARGET=Sitelist ADAPTER=#<Chewy::Type::Adapter::Mongoid:0x007fdb9aa52878>"
"ADAPTERS: "
[
    [0] Chewy::Type::Adapter::ActiveRecord < Chewy::Type::Adapter::Orm,
    [1] Chewy::Type::Adapter::Mongoid < Chewy::Type::Adapter::Orm,
    [2] Chewy::Type::Adapter::Sequel < Chewy::Type::Adapter::Orm,
    [3] Chewy::Type::Adapter::Object < Chewy::Type::Adapter::Base
]
"INDEX: PortalIndex TARGET=Segment ADAPTER=#<Chewy::Type::Adapter::Mongoid:0x007fdb9aa628e0>"
"ADAPTERS: "
[
    [0] Chewy::Type::Adapter::ActiveRecord < Chewy::Type::Adapter::Orm,
    [1] Chewy::Type::Adapter::Mongoid < Chewy::Type::Adapter::Orm,
    [2] Chewy::Type::Adapter::Sequel < Chewy::Type::Adapter::Orm,
    [3] Chewy::Type::Adapter::Object < Chewy::Type::Adapter::Base
]
"INDEX: PortalIndex TARGET=PortalIndex::User ADAPTER=#<Chewy::Type::Adapter::Object:0x007fdb9b134a10>"
/Users/marnyon/.rvm/gems/ruby-2.0.0-p353@client_app/bundler/gems/chewy-6189149708e9/lib/chewy.rb:117: warning: already initialized constant PortalIndex::User
/Users/marnyon/.rvm/gems/ruby-2.0.0-p353@client_app/bundler/gems/chewy-6189149708e9/lib/chewy.rb:117: warning: previous definition of User was here
"ADAPTERS: "
[
    [0] Chewy::Type::Adapter::ActiveRecord < Chewy::Type::Adapter::Orm,
    [1] Chewy::Type::Adapter::Mongoid < Chewy::Type::Adapter::Orm,
    [2] Chewy::Type::Adapter::Sequel < Chewy::Type::Adapter::Orm,
    [3] Chewy::Type::Adapter::Object < Chewy::Type::Adapter::Base
]
"INDEX: PortalIndex TARGET=PortalIndex::Account ADAPTER=#<Chewy::Type::Adapter::Object:0x007fdb9b13c120>"
/Users/marnyon/.rvm/gems/ruby-2.0.0-p353@client_app/bundler/gems/chewy-6189149708e9/lib/chewy.rb:117: warning: already initialized constant PortalIndex::Account
/Users/marnyon/.rvm/gems/ruby-2.0.0-p353@client_app/bundler/gems/chewy-6189149708e9/lib/chewy.rb:117: warning: previous definition of Account was here
"ADAPTERS: "
[
    [0] Chewy::Type::Adapter::ActiveRecord < Chewy::Type::Adapter::Orm,
    [1] Chewy::Type::Adapter::Mongoid < Chewy::Type::Adapter::Orm,
    [2] Chewy::Type::Adapter::Sequel < Chewy::Type::Adapter::Orm,
    [3] Chewy::Type::Adapter::Object < Chewy::Type::Adapter::Base
]
```

**Comment by pyromaniac** [comment]
Nothing comes to my mind unfortunately. You have to debug it probably.

**Comment by trystant** [comment]
For the record, this turned out to be due to a dual require with the sidekiq code and was fixed by removing that unneeded 'require' statement. This can be closed, and thank much for your help @pyromaniac.

**Comment by pyromaniac** [comment]
Awesome! Always welcome.
