### ISSUE TITLE
Throwing unexpected error inside sneaker background job.

### ISSUE THREAD

**Issue by afghl** [toptal/chewy#427]
Hi. @pyromaniac . I've been in trouble using chewy in background job and found it difficult to trace the error.

Originally my sneaker job is: 

```ruby
class NiceOrderNotifyJob
  include SneakersPacker::CommonWorker
  from_queue "nice.pay_notify"

  def call(data)
    params = data.symbolize_keys
    logger.info " sneaker receive data is #{params}"
    # https://github.com/toptal/chewy/issues/419
    Chewy.strategy(:atomic) do
      Billing.receive_billing(params)
    end
    logger.info " billing is created!"
  end

end

```

- The method `Billing.receive_billing` will update some related indexed models. 
- The method inside will also call **RestClient** to send a post request to another host. (which I guessed is causing this issue.)

I got this error in PROD:
```
2016-09-17T23:45:46Z p-24635 t-13en9k ERROR:
 [worker-nice.pay_notify:1:ijglmr][#<Thread:0x00000007e3e890>][nice.pay_notify][#<Sneakers::Configuration:0x00000007e3e610>] 
 unexpected error [Exception error="can't create Thread: Resource temporarily unavailable" error_class=ThreadError backtrace=/home/bhuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:81:in `start',
 /home/bhuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:81:in `block in timeout',
 /home/bhuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout',
 /home/bhuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:878:in `connect',
 /home/bhuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:863:in `do_start',
 /home/bhuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:852:in `start',
 /home/bhuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:1398:in `request',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/rest-client-1.6.9/lib/restclient/net_http_ext.rb:51:in `request',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent.rb:428:in `disable_all_tracing',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:201:in `perform_request',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/client.rb:125:in `perform_request',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/actions/indices/exists.rb:46:in `block in exists',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/utils.rb:191:in `__rescue_from_not_found',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/actions/indices/exists.rb:45:in `exists',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy/index/actions.rb:15:in `exists?',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy/type/import.rb:24:in `import',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy/type/import.rb:58:in `import!',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy/strategy/atomic.rb:27:in `block in leave',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy/strategy/atomic.rb:27:in `each',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy/strategy/atomic.rb:27:in `all?',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy/strategy/atomic.rb:27:in `leave',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy/strategy.rb:54:in `tap',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy/strategy.rb:54:in `pop',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy/strategy.rb:62:in `ensure in wrap',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy/strategy.rb:62:in `wrap',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/chewy-0.8.3/lib/chewy.rb:173:in `strategy',
 /var/apps/nice/releases/20160914031151/app/jobs/nice_order_notify_job.rb:9:in `call',
 /var/apps/nice/shared/bundle/ruby/2.3.0/bundler/gems/sneakers_packer-c1f75944ad45/lib/sneakers_packer/common_worker.rb:17:in `work',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/sneakers-2.3.5/lib/sneakers/worker.rb:58:in `block (3 levels) in do_work',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/sneakers-2.3.5/lib/sneakers/metrics/logging_metrics.rb:10:in `timing',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/sneakers-2.3.5/lib/sneakers/worker.rb:54:in `block (2 levels) in do_work',
 /home/bhuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout',
 /home/bhuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/sneakers-2.3.5/lib/sneakers/worker.rb:53:in `block in do_work',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/thread-0.1.7/lib/thread/pool.rb:56:in `execute',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/thread-0.1.7/lib/thread/pool.rb:404:in `block (2 levels) in spawn_thread',
 /var/apps/nice/shared/bundle/ruby/2.3.0/gems/thread-0.1.7/lib/thread/pool.rb:371:in `loop']
2016-09-17T23:45:46Z p-24635 t-13en9k INFO: INC: work.NiceOrderNotifyJob.handled.error
```

It doesn't reproduce in production or development.

However, I checked the records in Production and was pretty sure that the code wasn't interrupt until it tried to make that post request through RestClient.

I've not been able to find anything relevant to my problem in the docs. Please advise.

**Comment by pyromaniac** [comment]
Hey, have never meet this before, but looks like some kind of http lib - threads rpoblem, nothing about chewy here probably.

**Comment by afghl** [comment]
Oh yeah, find out it is caused by linux thread limitation.  Closing this now.
