### ISSUE TITLE
Not work delete_all after update chewy

### ISSUE THREAD

**Issue by araslanov-e** [toptal/chewy#504]
Я обновил chewy до 0.9.0, также обновилась зависимость elasticsearch-api (= 5.0.4) в которой я так понял поменяли http method для удаления https://github.com/elastic/elasticsearch-ruby/commit/cbfd6ebfe55c057666cc6de67fe6d9fc2f117908
Так же в https://github.com/toptal/chewy/issues/454 увидел коммент что удаление теперь работает без Плагина, но по коду https://github.com/toptal/chewy/blob/c203ba7ebe28874480bb80de43f3d63ffcd5623d/lib/chewy/query.rb#L944 плагин обязательный
А может и вообще дело не в плагине, а в том что шлется HTTP_DELETE https://github.com/toptal/chewy/blob/c203ba7ebe28874480bb80de43f3d63ffcd5623d/lib/chewy/query.rb#L960

**Comment by pyromaniac** [comment]
У тебя какая версия эластика, для начала?

**Comment by araslanov-e** [comment]
Ой, не написал вообще ничего
Elasticsearch 2.3.0
Ruby 2.2.3
Rails 4.1.10

**Comment by pyromaniac** [comment]
Да, похоже, 0.9.0 сломана в этом плане - https://github.com/toptal/chewy/blob/v0.9.0/lib/chewy/query.rb#L940

Мне кажется, мастер должен сработать, забери его, он стабильный довольно, заодно сможешь новый DSL опробовать, если нет желания - то переключайся на старый временно, всё равно потом придётся новый юзать.

**Comment by araslanov-e** [comment]
беру master, получаю
```
 rails c
/home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- active_support/core_ext/hash/transform_values (LoadError)
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `require'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/bundler/gems/chewy-cae8f89568cf/lib/chewy.rb:10:in `<top (required)>'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/bundler-1.15.0/lib/bundler/runtime.rb:82:in `require'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/bundler-1.15.0/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `each'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `block in require'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `each'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `require'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/bundler-1.15.0/lib/bundler.rb:108:in `require'
        from /home/araslanov_e/Jobs/BIA/projects/collector/config/application.rb:7:in `<top (required)>'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:146:in `require'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:146:in `require_application_and_environment!'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /home/araslanov_e/.rvm/gems/ruby-2.2.3@collector/gems/railties-4.1.10/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by araslanov-e** [comment]
Беру master, получаю
```
which: no elasticsearch in (/usr/local/rvm/gems/ruby-2.1.6/bin:/usr/local/rvm/gems/ruby-2.1.6@global/bin:/usr/local/rvm/rubies/ruby-2.1.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
/usr/local/rvm/gems/ruby-2.1.6/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- active_support/core_ext/hash/transform_values (LoadError)
        from /usr/local/rvm/gems/ruby-2.1.6/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `require'
        from /usr/local/rvm/gems/ruby-2.1.6/bundler/gems/chewy-cae8f89568cf/lib/chewy.rb:10:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
        from /home/web/app/config/application.rb:7:in `<top (required)>'
        from /home/web/app/config/environment.rb:2:in `require'
        from /home/web/app/config/environment.rb:2:in `<top (required)>'
        from /home/web/app/spec/rails_helper.rb:19:in `require'
        from /home/web/app/spec/rails_helper.rb:19:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1181:in `require'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1181:in `block in requires='
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1181:in `each'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1181:in `requires='
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/configuration_options.rb:110:in `block in process_options_into'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/configuration_options.rb:109:in `each'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/configuration_options.rb:109:in `process_options_into'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/configuration_options.rb:22:in `configure'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:96:in `setup'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
        from /usr/local/rvm/gems/ruby-2.1.6/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.6/bin/rspec:22:in `load'
        from /usr/local/rvm/gems/ruby-2.1.6/bin/rspec:22:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by pyromaniac** [comment]
Хм, интересно, сейчас сделаю фикс для 4.1

**Comment by araslanov-e** [comment]
В общем я пока сделал так
```
gem 'chewy', '0.9.0'
gem 'elasticsearch', '<= 5.0.0'
```
И журналы и delete_all работают

**Comment by pyromaniac** [comment]
Да: вариант. Я починил мастер, попробуй, если есть желание.

**Comment by araslanov-e** [comment]
Попробовал, что то у нас коллизии с новым DSL

**Comment by pyromaniac** [comment]
Это да, иначе никак https://github.com/toptal/chewy/#legacy-dsl-incompatibilities
