### ISSUE TITLE
ES Normalizers don't seem to get defined

### ISSUE THREAD

**Issue by turboladen** [toptal/chewy#544]
I'm trying to define a [normalizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/normalizer.html) so I can lowercase a keyword in my mapping, but it doesn't seem to be getting defined via chewy. Is there, perhaps, another way to do this? I'm on chewy 0.9.0, ES 5.5.0.

Settings section:

```ruby
  settings 'index.mapping.total_fields.limit' => 1500,
           analysis: {
             analyzer: {
               urls_links_emails: {
                 type: 'custom',
                 tokenizer: 'uax_url_email'
               }
             },
             normalizer: {
               my_normalizer: {
                 type: 'custom',
                 char_filter: [],
                 filter: ['lowercase', 'asciifolding']
               }
             }
           }
```

...usage of the normalizer:

```ruby
    field :sub_season, type: 'keyword', normalizer: 'my_normalizer'
```

Attempting to create the mapping...

```
⟪kraken⟫  001:0> ThingsIndex.purge!
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"normalizer [my_normalizer] not found for field [lower_case]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [thing]: normalizer [my_normalizer] not found for field [lower_case]","caused_by":{"type":"mapper_parsing_exception","reason":"normalizer [my_normalizer] not found for field [lower_case]"}},"status":400}
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:202:in `__raise_transport_error'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:319:in `perform_request'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/skylight-1.4.0.beta/lib/skylight/probes/elasticsearch.rb:17:in `block (3 levels) in perform_request'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/skylight-1.4.0.beta/lib/skylight/probes/elasticsearch.rb:25:in `disable_skylight_probe'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/skylight-1.4.0.beta/lib/skylight/probes/elasticsearch.rb:16:in `block (2 levels) in perform_request'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/skylight-1.4.0.beta/lib/skylight/probes/net_http.rb:11:in `disable'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/skylight-1.4.0.beta/lib/skylight/probes/elasticsearch.rb:25:in `disable_skylight_probe'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/skylight-1.4.0.beta/lib/skylight/probes/elasticsearch.rb:15:in `block in perform_request'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:166:in `instrument'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/skylight-1.4.0.beta/lib/skylight/probes/elasticsearch.rb:9:in `perform_request'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/client.rb:131:in `perform_request'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/elasticsearch-api-5.0.4/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/elasticsearch-api-5.0.4/lib/elasticsearch/api/actions/indices/create.rb:86:in `create'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/chewy-0.9.0/lib/chewy/index/actions.rb:62:in `create!'
        from /Users/sloveless/Development/agrian/kraken/vendor/bundle/ruby/2.4.0/gems/chewy-0.9.0/lib/chewy/index/actions.rb:127:in `purge!'
...
```

**Comment by turboladen** [comment]
FWIW, I did a wireshark capture of the request made to ES when calling `ThingsIndex.reset!` and no `normalizer` object gets sent:

```json
{  
  "settings":{  
    "index.mapping.total_fields.limit":1500,
    "analysis":{  
      "analyzer":{  
        "urls_links_emails":{  
          "type":"custom",
          "tokenizer":"uax_url_email"
        }
      }
    }
  },
```

**Comment by turboladen** [comment]
Also tried using master (ff49175) and found the same problem.

**Comment by pyromaniac** [comment]
Ok, this looks like a bug, seems like `normalizer` is a new option there, so it is not supported by Chewy's tricky settings. You can try to submit a patch for it: https://github.com/toptal/chewy/blob/master/lib/chewy/index/settings.rb

**Comment by pyromaniac** [comment]
check out https://github.com/toptal/chewy/pull/545/

**Comment by pyromaniac** [comment]
Ha, it was automatically closed. Should be resolved, use the latest master

**Comment by turboladen** [comment]
FWIW, I finally got around to upgrading from 0.9.0 to 0.10.1 and I still get the error here.

```ruby
# app/chewy/my_things_index.rb
class MyThingsIndex < Chewy::Index
  settings 'index.mapping.total_fields.limit' => 2000,
           analysis: {
             analyzer: {
               urls_links_emails: {
                 type: 'custom',
                 tokenizer: 'uax_url_email'
               }
             },
             normalizer: {
               lower_case: {
                 type: 'custom',
                 char_filter: [],
                 filter: %w[lowercase asciifolding]
               }
             }
           }
```

```
kraken git:feature/AGDEV-25508 ❯ bin/rake chewy:reset
Running via Spring preloader in process 97597
Resetting MyThingsIndex
rake aborted!
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"normalizer [lower_case] not found for field [lower_case]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [my_thing]: normalizer [lower_case] not found for field [lower_case]","caused_by":{"type":"mapper_parsing_exception","reason":"normalizer [lower_case] not found for field [lower_case]"}},"status":400}
```

I'd been working with this monkeypatch while on 0.9.0; if I put it back in (and remove setting the normalizer in the `settings` call), my stuff works fine:

```ruby
module Chewy
  class Index
    class Settings
      alias old_to_hash to_hash

      def to_hash
        old_settings = old_to_hash

        old_settings[:settings][:analysis][:normalizer] = {
          lower_case: {
            type: 'custom',
            char_filter: [],
            filter: %w[lowercase asciifolding]
          }
        }

        old_settings
      end
    end
  end
end
```

**Comment by pyromaniac** [comment]
Ok, will check this out later. Or feel free to submit a fix!

**Comment by turboladen** [comment]
@pyromaniac thanks! If I get some time, I'll definitely make a PR!
