### ISSUE TITLE
rake chewy:reset fails with Chewy.search_class = Chewy::Query

### ISSUE THREAD

**Issue by Boudewijn26** [toptal/chewy#587]
I'm looking into moving to moving to ES5, for which I need the new DSL, but when I run `rake chewy:reset` I get the following error:
```
NoMethodError: undefined method `or' for #<Chewy::Stash::Journal::Query:0x000055716db51830>
/home/user/cmp/chewy/lib/chewy/stash.rb:54:in `block in for'
/home/user/cmp/chewy/lib/chewy/stash.rb:52:in `each'
/home/user/cmp/chewy/lib/chewy/stash.rb:52:in `for'
/home/user/cmp/chewy/lib/chewy/stash.rb:30:in `entries'
/home/user/cmp/chewy/lib/chewy/journal.rb:26:in `apply'
/home/user/cmp/chewy/lib/chewy/index/actions.rb:192:in `reset!'
/home/user/cmp/chewy/lib/chewy/rake_helper.rb:299:in `reset_one'
/home/user/cmp/chewy/lib/chewy/rake_helper.rb:42:in `block (2 levels) in reset'
/home/user/cmp/chewy/lib/chewy/rake_helper.rb:41:in `each'
/home/user/cmp/chewy/lib/chewy/rake_helper.rb:41:in `block in reset'
/home/user/cmp/chewy/lib/chewy/rake_helper.rb:220:in `block (2 levels) in subscribed_task_stats'
/home/user/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:178:in `subscribed'
/home/user/cmp/chewy/lib/chewy/rake_helper.rb:219:in `block in subscribed_task_stats'
/home/user/.rvm/gems/ruby-2.4.2/gems/activesupport-5.1.4/lib/active_support/notifications.rb:178:in `subscribed'
/home/user/cmp/chewy/lib/chewy/rake_helper.rb:218:in `subscribed_task_stats'
/home/user/cmp/chewy/lib/chewy/rake_helper.rb:40:in `reset'
/home/user/cmp/chewy/lib/tasks/chewy.rake:26:in `block (2 levels) in <top (required)>'
/home/user/.rvm/gems/ruby-2.4.2/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

I've looked into this and it appears that `Stash` expects the old DSL. Am I doing something wrong or is `rake chewy:reset` not supported in the new DSL?

**Comment by pyromaniac** [comment]
Stash actually uses new DSL. `Chewy::Query` is actually an old DSL. `Chewy::Search::Request` is the new one. YOu definitely have found a but, but there might be a workaround: try to monkeypatch this method https://github.com/toptal/chewy/blob/master/lib/chewy/search.rb#L88 for the stash class so it will use hardcoded `Chewy::Search::Request` instead of `Chewy.search_class`

**Comment by Boudewijn26** [comment]
Ah, thanks! I've taking the liberty of creating a PR to fix the description. I can confirm monkeypatching to `Chewy::Search::Request` works, but fear this may break even more.
