### ISSUE TITLE
uninitialized constant Chewy::Search::Parameters::Id when updating from 0.9.0

### ISSUE THREAD

**Issue by bastoune** [toptal/chewy#608]
Using elasticSearch `2.4.6`

I am currently stuck to the 0.9.0 version of Chewy because when I try to upgrade i get this error
`uninitialized constant Chewy::Search::Parameters::Id `
 for example :
```
     Failure/Error: subject {get '/api/v2/user_searches', options.merge(token: user.token[:value])}
     NameError:
       uninitialized constant Chewy::Search::Parameters::Id
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:263:in `const_get'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:263:in `block in constantize'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `each'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `inject'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/inflector/methods.rb:259:in `constantize'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/search/parameters.rb:19:in `block in storages'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/search/parameters.rb:125:in `values_at'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/search/parameters.rb:125:in `assert_storages'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/search/parameters.rb:72:in `only!'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/search/request.rb:762:in `block in only'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/search/request.rb:946:in `instance_exec'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/search/request.rb:946:in `block in chain'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/search/request.rb:946:in `tap'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/search/request.rb:946:in `chain'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/search/request.rb:762:in `only'
     # ./app/controllers/api/v2/user_searches_controller.rb:7:in `show'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:198:in `process_action'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:117:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/sentry-raven-2.7.1/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `instance_exec'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:441:in `block in make_lambda'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:312:in `block in halting'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:497:in `block in around'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:505:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `block in instrument'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `instrument'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:137:in `process'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionview-4.2.10/lib/action_view/rendering.rb:30:in `process'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_controller/metal.rb:196:in `dispatch'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_controller/metal.rb:237:in `block in action'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:43:in `serve'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:43:in `block in serve'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `each'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `serve'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:817:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-pjax-1.0.0/lib/rack/pjax.rb:12:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/middleware/flash.rb:260:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/dragonfly-1.1.3/lib/dragonfly/middleware.rb:14:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:104:in `block in call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:69:in `cache'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:104:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-1.6.8/lib/rack/conditionalget.rb:25:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/remotipart-1.3.1/lib/remotipart/middleware.rb:32:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/middleware/flash.rb:260:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/middleware/cookies.rb:560:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/railtie.rb:19:in `block in call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/strategy.rb:70:in `wrap'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy.rb:200:in `strategy'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/chewy-0.10.1/lib/chewy/railtie.rb:19:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-contrib-1.8.0/lib/rack/contrib/runtime.rb:18:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/dragonfly-1.1.3/lib/dragonfly/cookie_monster.rb:9:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/middleware/static.rb:120:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/sentry-raven-2.7.1/lib/raven/integrations/rack.rb:51:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/rack-test-0.6.3/lib/rack/test.rb:124:in `request'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/testing/integration.rb:297:in `process'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/testing/integration.rb:32:in `get'
     # /home/bastien/.rvm/gems/ruby-2.3.4/gems/actionpack-4.2.10/lib/action_dispatch/testing/integration.rb:346:in `block (2 levels) in <module:Runner>'
     # ./spec/requests/api/v2/user_searches_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/requests/api/v2/user_searches_spec.rb:35:in `block (2 levels) in <top (required)>'
```

Here is my user index code :

```
# frozen_string_literal: true
class UsersIndex < Chewy::Index
  settings analysis: {
      analyzer: {
          sorted: {
              tokenizer: 'keyword',
              filter: %w(lowercase asciifolding)
          },
          white: {
              tokenizer: 'whitespace',
              filter: %w(lowercase asciifolding)
          },
          wide_ngram_analyzer: {
              tokenizer: 'ngram_tokenizer',
              filter: ['lowercase']
          }
      },
      tokenizer: {
          ngram_tokenizer: {
              type: 'nGram',
              min_gram: 2,
              max_gram: 10
          }
      }
  }

  define_type User, delete_if: :deleted_at? do
    field :firstname, type: 'multi_field' do
      field :firstname, analyzer: 'french'
      field :exact, analyzer: 'white'
      field :partial, analyzer: 'wide_ngram_analyzer'
    end

    field :lastname, type: 'multi_field' do
      field :lastname, analyzer: 'french'
      field :exact, analyzer: 'white'
      field :partial, analyzer: 'wide_ngram_analyzer'
    end

    field :email, type: 'multi_field' do
      field :email, analyzer: 'french'
      field :exact, analyzer: 'white'
      field :partial, analyzer: 'wide_ngram_analyzer'
    end


    field :created_at, type: 'date', include_in_all: false, value: -> { created_at }
  end
end

```

**Comment by pyromaniac** [comment]
Are you trying to update chewy? Try to read this: https://github.com/toptal/chewy#search-requests

**Comment by bastoune** [comment]
Solved it updating it

**Comment by sp2410** [comment]
@bastoune how did you solve it? what lines of code you updated ?

**Comment by pyromaniac** [comment]
You need to use new DSL style. There are no variables there. Post a particular piece of code so I could answer more precise

**Comment by bjeanes** [comment]
For me, this was because I was doing `.only(:id)`.

This doesn't seem to be listed as a breaking change anywhere in the changelog file, but I had to change this to `.source(:id)`. The README mentions that the `only` and `except` methods have new meanings now.
