### ISSUE TITLE
`.search_type` and `.preferences` always error

### ISSUE THREAD

**Issue by paulsuda** [toptal/chewy#642]
I have a query like this, which works just fine...

```
UsersIndex.query(match: {name: 'test'}).object_hash
```

Following [the docs](https://github.com/toptal/chewy/blob/master/lib/chewy/search/request.rb#L403),  I tried something like this to use the user ID to guarantee the same shards respond for a give user...

```
UsersIndex.query(match: {name: 'test'}).preference('MY_USER_ID_STRING').object_hash
```
... this throws this error...

```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [preference].","line":1,"col":15}],"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [preference].","line":1,"col":15},"status":400}
from /home/vagrant/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:202:in `__raise_transport_error'
```
... which is not that surprising, it looks like it's putting it in the body. This can be seen inspecting with `binding.pry`...

```
[42] pry(main)> UsersIndex.query(match: {name: 'test'}).preference('user_id_string')
=> <UsersIndex::Query {:index=>["users"], :type=>["user"], :body=>{:preference=>"user_id_string", :query=>{:match=>{:name=>"test"}}}}>
```

... same thing happens when I try to set a `search_type` like this according to [the docs](https://github.com/toptal/chewy/blob/master/lib/chewy/search/request.rb#L402)...

```
UsersIndex.query(match: {name: 'test'}).search_type(:dfs_query_then_fetch).object_hash
```
... it gives a similar error ...
```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [search_type].","line":1,"col":16}],"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [search_type].","line":1,"col":16},"status":400}
from /home/vagrant/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:202:in `__raise_transport_error'
```
... also because it's putting `search_type` in the query body.

Elasticsearch [docs say both of those should be in the query string](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-request-preference.html) instead.

I looked around and tried to find where to fix this, but haven't had time yet to really figure out the Chewy code base. Hopefully this is an easy quick fix for someone that knows their way around? Thanks to anyone who can help with this!

**Comment by sp2410** [comment]
Any solution to this ? I am having the same problem

**Comment by pyromaniac** [comment]
It actually looks like an `elasticsearch-ruby` issue. Its API accepts everything and should decide where to put particular params. Try to update it. Or downgrade.

**Comment by mmarini** [comment]
I've been having the same issue attempting to set the search type to `dfs_query_then_fetch`.

I'm on `elasticsearch-ruby` version 5.0.5. When Chewy calls elasticsearch-ruby's search method, 

https://github.com/elastic/elasticsearch-ruby/blob/86a36ec0db704b2a62dd4d5fe9edf887625b1826/elasticsearch-api/lib/elasticsearch/api/actions/search.rb#L173

the `__validate_and_extract_params` method will only parse the keys at the first level of the hash passed in. `search_type` is being missed because it's within the `body` key of the hash.

I think chewy should not be putting `search_type` within the body, but at a level above

**Comment by pyromaniac** [comment]
Hey, try the latest master

**Comment by yonnage** [comment]
Using the latest master,  **.preference** isn't working but **.search_type** is.

Looks like preference is added to the body instead of the query string.

```
UsersIndex.query(match: {name: 'test'}).preference('MY_USER_ID_STRING').render

{:index=>["users"], :type=>["user"], :body=>{:preference=>"MY_USER_ID_STRING", :query=>{:match=>{:name=>"test"}}}}

```
and errors with...

```
UsersIndex.query(match: {name: 'test'}).preference('MY_USER_ID_STRING').object_hash

Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"search_parse_exception","reason":"failed to parse search source. unknown search element [preference]","line":1,"col":15}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":...

```

Also tested .search_type which is added to the query string and does appear to work.

Does **preference** need to be added to the list of QUERY_STRING_STORAGES?
