### ISSUE TITLE
can't modify frozen Array when loading under Rails 5.2

### ISSUE THREAD

**Issue by aselder** [toptal/chewy#652]
We're trying to upgrade our app to Rails 5.2 and we're getting an error when chewy tries to insert the RequestStrategy middleware.

```
Failure/Error: require File.expand_path("../../config/environment", __FILE__)

RuntimeError:
  can't modify frozen Array
# /Users/aselder/.rvm/gems/ruby-2.4.4@usertesting-orders/gems/actionpack-5.2.1/lib/action_dispatch/middleware/stack.rb:76:in `insert'
# /Users/aselder/.rvm/gems/ruby-2.4.4@usertesting-orders/gems/actionpack-5.2.1/lib/action_dispatch/middleware/stack.rb:76:in `insert'
# /Users/aselder/.rvm/gems/ruby-2.4.4@usertesting-orders/gems/actionpack-5.2.1/lib/action_dispatch/middleware/stack.rb:83:in `insert_after'
# /Users/aselder/.rvm/gems/ruby-2.4.4@usertesting-orders/gems/chewy-0.9.0/lib/chewy/railtie.rb:70:in `block in <class:Railtie>'
# /Users/aselder/.rvm/gems/ruby-2.4.4@usertesting-orders/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
# /Users/aselder/.rvm/gems/ruby-2.4.4@usertesting-orders/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
# /Users/aselder/.rvm/gems/ruby-2.4.4@usertesting-orders/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
# /Users/aselder/.rvm/gems/ruby-2.4.4@usertesting-orders/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
# /Users/aselder/.rvm/gems/ruby-2.4.4@usertesting-orders/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
# /Users/aselder/.rvm/gems/ruby-2.4.4@usertesting-orders/gems/railties-5.2.1/lib/rails/railtie.rb:190:in `public_send'
# /Users/aselder/.rvm/gems/ruby-2.4.4@usertesting-orders/gems/railties-5.2.1/lib/rails/railtie.rb:190:in `method_missing'
# ./config/environment.rb:5:in `<main>'
```

I realize that this is an old version of Chewy, but the Railtie code on master is the same for inserting the middleware.

**Comment by aselder** [comment]
PR submitted: https://github.com/toptal/chewy/pull/658

**Comment by dalthon** [comment]
I was unable to reproduce it. Could you give more info so I could try to do it?

I see that you said that you were using an old version of Chewy, this still happens? If so I would reopen this
