### ISSUE TITLE
Failed to parse value [1] as only [true] or [false] are allowed. Error when I do chewy:reset

### ISSUE THREAD

**Issue by dbachinin** [toptal/chewy#725]
Hello! I have `elasticsearch:6.8.5` in docker image. (I use dokku Paas service) and chewy 5.1 service.
And when I ran the 'rake chewy:reset' command, I get this error:
```
task with --trace)
herokuishuser@7fa064962d35:~$ rake chewy:reset --trace
** Invoke chewy:reset (first_time)
** Invoke environment (first_time)
** Execute environment
[DOORKEEPER] native_redirect_uri has been deprecated and will soon be removed
** Execute chewy:reset
Resetting CompaniesIndex
  Imported CompaniesIndex::Company in 1s, stats: index 47
  Imported Chewy::Stash::Specification::Specification in 1s, stats: index 1
Resetting CustomersIndex
rake aborted!
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse value [1] as only [true] or [false] are allowed."}],"type":"illegal_argument_exception","reason":"Failed to parse value [1] as only [true] or [false] are allowed."},"status":400}
/app/vendor/bundle/ruby/2.6.0/gems/elasticsearch-transport-7.7.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error'
/app/vendor/bundle/ruby/2.6.0/gems/elasticsearch-transport-7.7.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
/app/vendor/bundle/ruby/2.6.0/gems/elasticsearch-transport-7.7.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
/app/vendor/bundle/ruby/2.6.0/gems/elasticsearch-transport-7.7.0/lib/elasticsearch/transport/client.rb:163:in `perform_request'
/app/vendor/bundle/ruby/2.6.0/gems/elasticsearch-api-7.7.0/lib/elasticsearch/api/namespace/common.rb:25:in `perform_request'
/app/vendor/bundle/ruby/2.6.0/gems/elasticsearch-api-7.7.0/lib/elasticsearch/api/actions/indices/create.rb:35:in `create'
/app/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/index/actions.rb:62:in `create!'
/app/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/index/actions.rb:176:in `reset!'
/app/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/rake_helper.rb:299:in `reset_one'
/app/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/rake_helper.rb:42:in `block (2 levels) in reset'
/app/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/rake_helper.rb:41:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/rake_helper.rb:41:in `block in reset'
/app/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/rake_helper.rb:220:in `block (2 levels) in subscribed_task_stats'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:180:in `subscribed'
/app/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/rake_helper.rb:219:in `block in subscribed_task_stats'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:180:in `subscribed'
/app/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/rake_helper.rb:218:in `subscribed_task_stats'
/app/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/rake_helper.rb:40:in `reset'
/app/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/tasks/chewy.rake:26:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/app/bin/rake:4:in `<main>'
Tasks: TOP => chewy:reset
```
I know this is because of `pretty=1` parameter in request.
In how replace it to `pretty=true` instead?

**Comment by dalthon** [comment]
Hi, I noticed that you had this error while using elasticsearch 6.8.5.
By that time we didn't support Elasticsearch 6, but now we do!
Could you check latest version and to check if this still happens?
BTW, soon we hope to add support to ES 7 as well!

**Comment by dalthon** [comment]
Closed due to inactivity. Will reopen if now since 6.8 is supported and this is not supposed to be happening anymore
